server:
  port: 9017
spring:
  datasource:
    #url: jdbc:mysql://10.10.10.200:3306/flowable?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    #username: root
    #password: JfAsdf0605
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver 驱动5 带cj驱动8需要增加时区配置
    druid:
      initialSize: 1
      minIdle: 1
      maxActive: 10
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
  profiles:
        include: jdbc

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.demo.updown.entity
  global-config:
    db-config:
      column-underline: false
      #配置逻辑删除 删除为1
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      jdbc-type-for-null: 'null'
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      database-id: mysql
    configuration-properties:
      blobType: BLOB
      boolValue: TRUE
      prefix:
logging:
  level:
    com.demo.updown.mapper: debug
fdfs:
  so-timeout: 3000       # 读取时间
  connect-timeout: 600   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表106.15.61.115
    - 119.45.115.231:22122
upload:
  base-url: http://119.45.115.231/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - image/jpg